Repository psi-projekat/psi-projekat, pull requests merged in 2019-06, with the labels that each got.

#122 Упутства за покретање апликације
  building.md
Labels: doc, meta

#118 Dodavanje engleskog jezika
  src/www/projects/main/strings/locales/en-us/main.json
Labels: translation, web app

#120 Измењен Readme.md
  readme.md
Labels: meta

#123 Obrisani nepotrebni batch fajlovi
  find.bat
  init.bat
  push.bat
  test.bat
Labels: server

#124 Исправак озбиљног bug-а
  src/node/prog-langs/langs/functional/interpreter.js
Labels: prog langs
